name: Create new Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    if: ${{ github.actor_id == '2507459' || github.actor_id == '68259537' }}

    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --generate-notes